services:
  src:
    build:
      context: .
      dockerfile: Dockerfile
    image: p3-ae1-2026_g10-m6:2.0
    ports: ["3001:3001"]
    environment:
      PORT: 3001
      RF6_API_URL: ${RF6_API_URL:-http://host.docker.internal:3000}
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: src-container

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: ["5672:5672", "15672:15672"]
    container_name: rabbitmq-container
