import { createHmac, timingSafeEqual } from "node:crypto";
import {
  ITripVerificationService,
  TripProofClaims,
  TripVerificationResult,
} from "../../domain/ports/ITripVerificationService.js";

export class HmacTripVerificationService implements ITripVerificationService {
  private readonly secretKey: string;

  constructor(secretKey: string = "secret-key-shared-between-trip-and-customer-service") {
    this.secretKey = secretKey;
  }

  /**
   * Generates a signed token (payload.signature in base64url).
   * Typically generated by Trip Service upon trip completion and verified here in Customer Service.
   */
  public generateProofToken(claims: Omit<TripProofClaims, "expiresAt">, ttlSeconds: number = 86400): string {
    const fullClaims: TripProofClaims = {
      ...claims,
      expiresAt: Math.floor(Date.now() / 1000) + ttlSeconds,
    };

    const payloadJson = JSON.stringify(fullClaims);
    const payloadB64 = Buffer.from(payloadJson).toString("base64url");
    const signature = this.sign(payloadB64);

    return `${payloadB64}.${signature}`;
  }

  public async verifyTripCompletionProof(
    proofToken: string,
    expectedCustomerId: string,
    expectedTripId: string,
    expectedDriverId: string
  ): Promise<TripVerificationResult> {
    if (!proofToken || typeof proofToken !== "string") {
      return { isValid: false, errorMessage: "El token de verificación de viaje no fue proporcionado." };
    }

    const parts = proofToken.split(".");
    if (parts.length !== 2) {
      return { isValid: false, errorMessage: "Formato de token de verificación inválido." };
    }

    const [payloadB64, signature] = parts;
    const expectedSignature = this.sign(payloadB64);

    // Timing-safe comparison to prevent side-channel attacks
    const sigBuf = Buffer.from(signature);
    const expectedSigBuf = Buffer.from(expectedSignature);

    if (sigBuf.length !== expectedSigBuf.length || !timingSafeEqual(sigBuf, expectedSigBuf)) {
      return { isValid: false, errorMessage: "Firma criptográfica del token de viaje inválida o alterada." };
    }

    try {
      const payloadJson = Buffer.from(payloadB64, "base64url").toString("utf-8");
      const claims: TripProofClaims = JSON.parse(payloadJson);

      const now = Math.floor(Date.now() / 1000);
      if (claims.expiresAt && claims.expiresAt < now) {
        return { isValid: false, errorMessage: "El token de verificación de viaje ha expirado." };
      }

      if (claims.status !== "COMPLETED") {
        return { isValid: false, errorMessage: `El estado del viaje no es COMPLETED. Estado actual: ${claims.status}` };
      }

      if (claims.customerId.toLowerCase() !== expectedCustomerId.toLowerCase()) {
        return { isValid: false, errorMessage: "El cliente en el token no coincide con el cliente emisor." };
      }

      if (claims.tripId.toLowerCase() !== expectedTripId.toLowerCase()) {
        return { isValid: false, errorMessage: "El ID de viaje en el token no coincide con el viaje a calificar." };
      }

      if (claims.driverId.toLowerCase() !== expectedDriverId.toLowerCase()) {
        return { isValid: false, errorMessage: "El ID del conductor en el token no coincide con el conductor indicado." };
      }

      return {
        isValid: true,
        claims,
      };
    } catch {
      return { isValid: false, errorMessage: "Error al deserializar los claims del token de viaje." };
    }
  }

  private sign(data: string): string {
    return createHmac("sha256", this.secretKey).update(data).digest("base64url");
  }
}
